# Matrix Function

What is a matrix?

In [4]:
A = [1 2 3;
     4 5 6;
     7 8 9]

3×3 Array{Int64,2}:
 1  2  3
 4  5  6
 7  8  9

What is the size of the matrix?

In [17]:
size(A)

(3, 3)

How many dimensions does this matrix have?

In [7]:
n_dims(A) = length(size(A))
n_dims(A)

2

How can I multiply a matrix

In [8]:
function multiply(A, B)
    a_dims = n_dims(A)
    if a_dims ≠ 2 throw("Error: Expected matrix to have size 2 got $a_dims") end
    b_dims = n_dims(B)
    if b_dims ≠ 2 throw("Error: Expected matrix to have size 2 got $b_dims") end
    a_size = size(A)
    b_size = size(B)
    if a_size[2] ≠ b_size[1] throw("Error: Matrix of size $a_size can not multiply size $b_size") end
    shared_size = a_size[2]
    C = Matrix{Float64}(undef, a_size[1], b_size[2])
    for row in 1:size(C)[1]
        for column in 1:size(C)[2]
            for shared in 1:shared_size
                C[row, column] += A[row, shared] * B[shared, column]
            end
        end
    end
    return C
end
A = [ 1 2;
      3 4]
multiply(A,A)

2×2 Array{Float64,2}:
  7.0  10.0
 15.0  22.0

How can I transpose a matrix?

In [9]:
function T(A)
    A′ = Array{Float64, 2}(undef, size(A)[2], size(A)[1])
    for row ∈ 1:size(A′)[1]
        for column ∈ 1:size(A′)[2]
            A′[row, column] = A[column, row]
        end
    end
    
    return A′
end
A = [ 1 2;
      3 4]
T(A)

2×2 Array{Float64,2}:
 1.0  3.0
 2.0  4.0

How would I do a projection?

In [10]:
function project(A, B)
    middle = Base.inv(multiply(T(A), A))
    P = multiply(multiply(A, middle), T(A))
    p = multiply(P, B)
    return p
end
project(A, A)

2×2 Array{Float64,2}:
 1.0  2.0
 3.0  4.0

In [15]:
function gram_schmit(A)
    n, m = size(A)
    A′ = copy(A)
    for i ∈ 1:n
        A′[i,1] = A[i,1]
    end
    for col in 2:m
        base = reshape(A′[:,1:(col-1)], n, col-1)
        cur = reshape(A′[:, col], n, 1)
        p = project(base, cur)
        cur = cur - p
        for i ∈ 1:n
            A′[i,col] = cur[i,1]
        end
    end
    return A′
end
A = [ 1 0  0.0;
      -1 1  0;
      0 -1 1;
    0 0 -1]
gram_schmit(A)

4×3 Array{Float64,2}:
  1.0   0.5            0.333333
 -1.0   0.5            0.333333
  0.0  -1.0            0.333333
  0.0  -6.94654e-310  -1.0